// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/probe/v1/probe.proto

package probev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Report is one sample from an agent. A sample that does not fit one packet
// is split across several Reports sharing ts; the server merges them field
// by field. A field the agent could not read is left out.
type Report struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`  // sample time, unix seconds, a multiple of the report interval
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`  // random, echoed back in Ack
	Sys           *SysInfo               `protobuf:"bytes,3,opt,name=sys,proto3" json:"sys,omitempty"` // on start and hourly
	Cpu           *CPU                   `protobuf:"bytes,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Load          *Load                  `protobuf:"bytes,5,opt,name=load,proto3" json:"load,omitempty"`
	Mem           *Mem                   `protobuf:"bytes,6,opt,name=mem,proto3" json:"mem,omitempty"`
	Sockets       *Sockets               `protobuf:"bytes,7,opt,name=sockets,proto3" json:"sockets,omitempty"`
	Disks         []*Disk                `protobuf:"bytes,8,rep,name=disks,proto3" json:"disks,omitempty"` // every 60s
	Net           []*NetRate             `protobuf:"bytes,9,rep,name=net,proto3" json:"net,omitempty"`
	Traffic       []*IfaceTraffic        `protobuf:"bytes,10,rep,name=traffic,proto3" json:"traffic,omitempty"`
	Pings         []*Ping                `protobuf:"bytes,11,rep,name=pings,proto3" json:"pings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_proto_probe_v1_probe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_v1_probe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_proto_probe_v1_probe_proto_rawDescGZIP(), []int{0}
}

func (x *Report) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Report) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Report) GetSys() *SysInfo {
	if x != nil {
		return x.Sys
	}
	return nil
}

func (x *Report) GetCpu() *CPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *Report) GetLoad() *Load {
	if x != nil {
		return x.Load
	}
	return nil
}

func (x *Report) GetMem() *Mem {
	if x != nil {
		return x.Mem
	}
	return nil
}

func (x *Report) GetSockets() *Sockets {
	if x != nil {
		return x.Sockets
	}
	return nil
}

func (x *Report) GetDisks() []*Disk {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *Report) GetNet() []*NetRate {
	if x != nil {
		return x.Net
	}
	return nil
}

func (x *Report) GetTraffic() []*IfaceTraffic {
	if x != nil {
		return x.Traffic
	}
	return nil
}

func (x *Report) GetPings() []*Ping {
	if x != nil {
		return x.Pings
	}
	return nil
}

type SysInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"` // PRETTY_NAME from /etc/os-release
	Kernel        string                 `protobuf:"bytes,3,opt,name=kernel,proto3" json:"kernel,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Cores         uint32                 `protobuf:"varint,5,opt,name=cores,proto3" json:"cores,omitempty"`
	BootTime      int64                  `protobuf:"varint,6,opt,name=boot_time,json=bootTime,proto3" json:"boot_time,omitempty"` // unix seconds; 0 = unknown
	AgentVersion  string                 `protobuf:"bytes,7,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysInfo) Reset() {
	*x = SysInfo{}
	mi := &file_proto_probe_v1_probe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysInfo) ProtoMessage() {}

func (x *SysInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_v1_probe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysInfo.ProtoReflect.Descriptor instead.
func (*SysInfo) Descriptor() ([]byte, []int) {
	return file_proto_probe_v1_probe_proto_rawDescGZIP(), []int{1}
}

func (x *SysInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SysInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SysInfo) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *SysInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SysInfo) GetCores() uint32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *SysInfo) GetBootTime() int64 {
	if x != nil {
		return x.BootTime
	}
	return 0
}

func (x *SysInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type CPU struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usage         float32                `protobuf:"fixed32,1,opt,name=usage,proto3" json:"usage,omitempty"`     // percent, 0-100
	Steal         float32                `protobuf:"fixed32,2,opt,name=steal,proto3" json:"steal,omitempty"`     // percent, 0-100
	Softirq       float32                `protobuf:"fixed32,3,opt,name=softirq,proto3" json:"softirq,omitempty"` // percent, part of usage: mostly network packet processing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPU) Reset() {
	*x = CPU{}
	mi := &file_proto_probe_v1_probe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPU) ProtoMessage() {}

func (x *CPU) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_v1_probe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPU.ProtoReflect.Descriptor instead.
func (*CPU) Descriptor() ([]byte, []int) {
	return file_proto_probe_v1_probe_proto_rawDescGZIP(), []int{2}
}

func (x *CPU) GetUsage() float32 {
	if x != nil {
		return x.Usage
	}
	return 0
}

func (x *CPU) GetSteal() float32 {
	if x != nil {
		return x.Steal
	}
	return 0
}

func (x *CPU) GetSoftirq() float32 {
	if x != nil {
		return x.Softirq
	}
	return 0
}

type Load struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	L1            float32                `protobuf:"fixed32,1,opt,name=l1,proto3" json:"l1,omitempty"`
	L5            float32                `protobuf:"fixed32,2,opt,name=l5,proto3" json:"l5,omitempty"`
	L15           float32                `protobuf:"fixed32,3,opt,name=l15,proto3" json:"l15,omitempty"`
	Threads       uint32                 `protobuf:"varint,4,opt,name=threads,proto3" json:"threads,omitempty"` // all threads on the host, from /proc/loadavg
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Load) Reset() {
	*x = Load{}
	mi := &file_proto_probe_v1_probe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Load) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Load) ProtoMessage() {}

func (x *Load) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_v1_probe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Load.ProtoReflect.Descriptor instead.
func (*Load) Descriptor() ([]byte, []int) {
	return file_proto_probe_v1_probe_proto_rawDescGZIP(), []int{3}
}

func (x *Load) GetL1() float32 {
	if x != nil {
		return x.L1
	}
	return 0
}

func (x *Load) GetL5() float32 {
	if x != nil {
		return x.L5
	}
	return 0
}

func (x *Load) GetL15() float32 {
	if x != nil {
		return x.L15
	}
	return 0
}

func (x *Load) GetThreads() uint32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

type Mem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` // bytes
	Used          uint64                 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`   // total - MemAvailable
	SwapTotal     uint64                 `protobuf:"varint,3,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapUsed      uint64                 `protobuf:"varint,4,opt,name=swap_used,json=swapUsed,proto3" json:"swap_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mem) Reset() {
	*x = Mem{}
	mi := &file_proto_probe_v1_probe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mem) ProtoMessage() {}

func (x *Mem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_v1_probe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mem.ProtoReflect.Descriptor instead.
func (*Mem) Descriptor() ([]byte, []int) {
	return file_proto_probe_v1_probe_proto_rawDescGZIP(), []int{4}
}

func (x *Mem) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Mem) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *Mem) GetSwapTotal() uint64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *Mem) GetSwapUsed() uint64 {
	if x != nil {
		return x.SwapUsed
	}
	return 0
}

// Sockets in use, IPv4 + IPv6, from /proc/net/sockstat and sockstat6.
type Sockets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tcp           uint32                 `protobuf:"varint,1,opt,name=tcp,proto3" json:"tcp,omitempty"` // other than TIME_WAIT, listening ones included
	Udp           uint32                 `protobuf:"varint,2,opt,name=udp,proto3" json:"udp,omitempty"`
	TcpTw         uint32                 `protobuf:"varint,3,opt,name=tcp_tw,json=tcpTw,proto3" json:"tcp_tw,omitempty"` // TIME_WAIT
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sockets) Reset() {
	*x = Sockets{}
	mi := &file_proto_probe_v1_probe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sockets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sockets) ProtoMessage() {}

func (x *Sockets) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_v1_probe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sockets.ProtoReflect.Descriptor instead.
func (*Sockets) Descriptor() ([]byte, []int) {
	return file_proto_probe_v1_probe_proto_rawDescGZIP(), []int{5}
}

func (x *Sockets) GetTcp() uint32 {
	if x != nil {
		return x.Tcp
	}
	return 0
}

func (x *Sockets) GetUdp() uint32 {
	if x != nil {
		return x.Udp
	}
	return 0
}

func (x *Sockets) GetTcpTw() uint32 {
	if x != nil {
		return x.TcpTw
	}
	return 0
}

type Disk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mount         string                 `protobuf:"bytes,1,opt,name=mount,proto3" json:"mount,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // bytes
	Used          uint64                 `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	Avail         uint64                 `protobuf:"varint,4,opt,name=avail,proto3" json:"avail,omitempty"` // available to unprivileged users, as df reports
	InodePct      float32                `protobuf:"fixed32,5,opt,name=inode_pct,json=inodePct,proto3" json:"inode_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_proto_probe_v1_probe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_v1_probe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_proto_probe_v1_probe_proto_rawDescGZIP(), []int{6}
}

func (x *Disk) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

func (x *Disk) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Disk) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *Disk) GetAvail() uint64 {
	if x != nil {
		return x.Avail
	}
	return 0
}

func (x *Disk) GetInodePct() float32 {
	if x != nil {
		return x.InodePct
	}
	return 0
}

type NetRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Iface         string                 `protobuf:"bytes,1,opt,name=iface,proto3" json:"iface,omitempty"`
	RxRate        uint64                 `protobuf:"varint,2,opt,name=rx_rate,json=rxRate,proto3" json:"rx_rate,omitempty"` // bytes per second
	TxRate        uint64                 `protobuf:"varint,3,opt,name=tx_rate,json=txRate,proto3" json:"tx_rate,omitempty"`
	RxPps         uint64                 `protobuf:"varint,4,opt,name=rx_pps,json=rxPps,proto3" json:"rx_pps,omitempty"` // packets per second
	TxPps         uint64                 `protobuf:"varint,5,opt,name=tx_pps,json=txPps,proto3" json:"tx_pps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetRate) Reset() {
	*x = NetRate{}
	mi := &file_proto_probe_v1_probe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetRate) ProtoMessage() {}

func (x *NetRate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_v1_probe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetRate.ProtoReflect.Descriptor instead.
func (*NetRate) Descriptor() ([]byte, []int) {
	return file_proto_probe_v1_probe_proto_rawDescGZIP(), []int{7}
}

func (x *NetRate) GetIface() string {
	if x != nil {
		return x.Iface
	}
	return ""
}

func (x *NetRate) GetRxRate() uint64 {
	if x != nil {
		return x.RxRate
	}
	return 0
}

func (x *NetRate) GetTxRate() uint64 {
	if x != nil {
		return x.TxRate
	}
	return 0
}

func (x *NetRate) GetRxPps() uint64 {
	if x != nil {
		return x.RxPps
	}
	return 0
}

func (x *NetRate) GetTxPps() uint64 {
	if x != nil {
		return x.TxPps
	}
	return 0
}

// IfaceTraffic is what one interface carried in the current billing period
// and in the one before it.
type IfaceTraffic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Iface         string                 `protobuf:"bytes,1,opt,name=iface,proto3" json:"iface,omitempty"`
	Cur           *Period                `protobuf:"bytes,2,opt,name=cur,proto3" json:"cur,omitempty"`
	Prev          *Period                `protobuf:"bytes,3,opt,name=prev,proto3" json:"prev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IfaceTraffic) Reset() {
	*x = IfaceTraffic{}
	mi := &file_proto_probe_v1_probe_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IfaceTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfaceTraffic) ProtoMessage() {}

func (x *IfaceTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_v1_probe_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfaceTraffic.ProtoReflect.Descriptor instead.
func (*IfaceTraffic) Descriptor() ([]byte, []int) {
	return file_proto_probe_v1_probe_proto_rawDescGZIP(), []int{8}
}

func (x *IfaceTraffic) GetIface() string {
	if x != nil {
		return x.Iface
	}
	return ""
}

func (x *IfaceTraffic) GetCur() *Period {
	if x != nil {
		return x.Cur
	}
	return nil
}

func (x *IfaceTraffic) GetPrev() *Period {
	if x != nil {
		return x.Prev
	}
	return nil
}

// Period is a billing period [start, end) and the bytes counted in it. The
// agent alone decides when periods begin; the server never computes one.
type Period struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int64                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"` // unix seconds
	End           int64                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Rx            uint64                 `protobuf:"varint,3,opt,name=rx,proto3" json:"rx,omitempty"`
	Tx            uint64                 `protobuf:"varint,4,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Period) Reset() {
	*x = Period{}
	mi := &file_proto_probe_v1_probe_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Period) ProtoMessage() {}

func (x *Period) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_v1_probe_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Period.ProtoReflect.Descriptor instead.
func (*Period) Descriptor() ([]byte, []int) {
	return file_proto_probe_v1_probe_proto_rawDescGZIP(), []int{9}
}

func (x *Period) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Period) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *Period) GetRx() uint64 {
	if x != nil {
		return x.Rx
	}
	return 0
}

func (x *Period) GetTx() uint64 {
	if x != nil {
		return x.Tx
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"` // peer name from the agent config
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`     // resolved address, empty if resolution failed
	Sent          uint32                 `protobuf:"varint,3,opt,name=sent,proto3" json:"sent,omitempty"`
	Lost          uint32                 `protobuf:"varint,4,opt,name=lost,proto3" json:"lost,omitempty"`
	Min           float32                `protobuf:"fixed32,5,opt,name=min,proto3" json:"min,omitempty"` // milliseconds, over replies only
	Avg           float32                `protobuf:"fixed32,6,opt,name=avg,proto3" json:"avg,omitempty"`
	Max           float32                `protobuf:"fixed32,7,opt,name=max,proto3" json:"max,omitempty"`
	Jitter        float32                `protobuf:"fixed32,8,opt,name=jitter,proto3" json:"jitter,omitempty"` // mean absolute difference of consecutive round trips
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_probe_v1_probe_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_v1_probe_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_probe_v1_probe_proto_rawDescGZIP(), []int{10}
}

func (x *Ping) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Ping) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Ping) GetSent() uint32 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *Ping) GetLost() uint32 {
	if x != nil {
		return x.Lost
	}
	return 0
}

func (x *Ping) GetMin() float32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Ping) GetAvg() float32 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *Ping) GetMax() float32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *Ping) GetJitter() float32 {
	if x != nil {
		return x.Jitter
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_probe_v1_probe_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_v1_probe_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_probe_v1_probe_proto_rawDescGZIP(), []int{11}
}

func (x *Ack) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_proto_probe_v1_probe_proto protoreflect.FileDescriptor

const file_proto_probe_v1_probe_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/probe/v1/probe.proto\x12\bprobe.v1\"\x83\x03\n" +
	"\x06Report\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x12#\n" +
	"\x03sys\x18\x03 \x01(\v2\x11.probe.v1.SysInfoR\x03sys\x12\x1f\n" +
	"\x03cpu\x18\x04 \x01(\v2\r.probe.v1.CPUR\x03cpu\x12\"\n" +
	"\x04load\x18\x05 \x01(\v2\x0e.probe.v1.LoadR\x04load\x12\x1f\n" +
	"\x03mem\x18\x06 \x01(\v2\r.probe.v1.MemR\x03mem\x12+\n" +
	"\asockets\x18\a \x01(\v2\x11.probe.v1.SocketsR\asockets\x12$\n" +
	"\x05disks\x18\b \x03(\v2\x0e.probe.v1.DiskR\x05disks\x12#\n" +
	"\x03net\x18\t \x03(\v2\x11.probe.v1.NetRateR\x03net\x120\n" +
	"\atraffic\x18\n" +
	" \x03(\v2\x16.probe.v1.IfaceTrafficR\atraffic\x12$\n" +
	"\x05pings\x18\v \x03(\v2\x0e.probe.v1.PingR\x05pings\"\xb9\x01\n" +
	"\aSysInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x16\n" +
	"\x06kernel\x18\x03 \x01(\tR\x06kernel\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x14\n" +
	"\x05cores\x18\x05 \x01(\rR\x05cores\x12\x1b\n" +
	"\tboot_time\x18\x06 \x01(\x03R\bbootTime\x12#\n" +
	"\ragent_version\x18\a \x01(\tR\fagentVersion\"K\n" +
	"\x03CPU\x12\x14\n" +
	"\x05usage\x18\x01 \x01(\x02R\x05usage\x12\x14\n" +
	"\x05steal\x18\x02 \x01(\x02R\x05steal\x12\x18\n" +
	"\asoftirq\x18\x03 \x01(\x02R\asoftirq\"R\n" +
	"\x04Load\x12\x0e\n" +
	"\x02l1\x18\x01 \x01(\x02R\x02l1\x12\x0e\n" +
	"\x02l5\x18\x02 \x01(\x02R\x02l5\x12\x10\n" +
	"\x03l15\x18\x03 \x01(\x02R\x03l15\x12\x18\n" +
	"\athreads\x18\x04 \x01(\rR\athreads\"k\n" +
	"\x03Mem\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x02 \x01(\x04R\x04used\x12\x1d\n" +
	"\n" +
	"swap_total\x18\x03 \x01(\x04R\tswapTotal\x12\x1b\n" +
	"\tswap_used\x18\x04 \x01(\x04R\bswapUsed\"D\n" +
	"\aSockets\x12\x10\n" +
	"\x03tcp\x18\x01 \x01(\rR\x03tcp\x12\x10\n" +
	"\x03udp\x18\x02 \x01(\rR\x03udp\x12\x15\n" +
	"\x06tcp_tw\x18\x03 \x01(\rR\x05tcpTw\"y\n" +
	"\x04Disk\x12\x14\n" +
	"\x05mount\x18\x01 \x01(\tR\x05mount\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x03 \x01(\x04R\x04used\x12\x14\n" +
	"\x05avail\x18\x04 \x01(\x04R\x05avail\x12\x1b\n" +
	"\tinode_pct\x18\x05 \x01(\x02R\binodePct\"\x7f\n" +
	"\aNetRate\x12\x14\n" +
	"\x05iface\x18\x01 \x01(\tR\x05iface\x12\x17\n" +
	"\arx_rate\x18\x02 \x01(\x04R\x06rxRate\x12\x17\n" +
	"\atx_rate\x18\x03 \x01(\x04R\x06txRate\x12\x15\n" +
	"\x06rx_pps\x18\x04 \x01(\x04R\x05rxPps\x12\x15\n" +
	"\x06tx_pps\x18\x05 \x01(\x04R\x05txPps\"n\n" +
	"\fIfaceTraffic\x12\x14\n" +
	"\x05iface\x18\x01 \x01(\tR\x05iface\x12\"\n" +
	"\x03cur\x18\x02 \x01(\v2\x10.probe.v1.PeriodR\x03cur\x12$\n" +
	"\x04prev\x18\x03 \x01(\v2\x10.probe.v1.PeriodR\x04prev\"P\n" +
	"\x06Period\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x03R\x03end\x12\x0e\n" +
	"\x02rx\x18\x03 \x01(\x04R\x02rx\x12\x0e\n" +
	"\x02tx\x18\x04 \x01(\x04R\x02tx\"\xa8\x01\n" +
	"\x04Ping\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x12\n" +
	"\x04sent\x18\x03 \x01(\rR\x04sent\x12\x12\n" +
	"\x04lost\x18\x04 \x01(\rR\x04lost\x12\x10\n" +
	"\x03min\x18\x05 \x01(\x02R\x03min\x12\x10\n" +
	"\x03avg\x18\x06 \x01(\x02R\x03avg\x12\x10\n" +
	"\x03max\x18\a \x01(\x02R\x03max\x12\x16\n" +
	"\x06jitter\x18\b \x01(\x02R\x06jitter\"\x17\n" +
	"\x03Ack\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03idsB8Z6github.com/shakespark/vps-probe/internal/proto/probev1b\x06proto3"

var (
	file_proto_probe_v1_probe_proto_rawDescOnce sync.Once
	file_proto_probe_v1_probe_proto_rawDescData []byte
)

func file_proto_probe_v1_probe_proto_rawDescGZIP() []byte {
	file_proto_probe_v1_probe_proto_rawDescOnce.Do(func() {
		file_proto_probe_v1_probe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_probe_v1_probe_proto_rawDesc), len(file_proto_probe_v1_probe_proto_rawDesc)))
	})
	return file_proto_probe_v1_probe_proto_rawDescData
}

var file_proto_probe_v1_probe_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_probe_v1_probe_proto_goTypes = []any{
	(*Report)(nil),       // 0: probe.v1.Report
	(*SysInfo)(nil),      // 1: probe.v1.SysInfo
	(*CPU)(nil),          // 2: probe.v1.CPU
	(*Load)(nil),         // 3: probe.v1.Load
	(*Mem)(nil),          // 4: probe.v1.Mem
	(*Sockets)(nil),      // 5: probe.v1.Sockets
	(*Disk)(nil),         // 6: probe.v1.Disk
	(*NetRate)(nil),      // 7: probe.v1.NetRate
	(*IfaceTraffic)(nil), // 8: probe.v1.IfaceTraffic
	(*Period)(nil),       // 9: probe.v1.Period
	(*Ping)(nil),         // 10: probe.v1.Ping
	(*Ack)(nil),          // 11: probe.v1.Ack
}
var file_proto_probe_v1_probe_proto_depIdxs = []int32{
	1,  // 0: probe.v1.Report.sys:type_name -> probe.v1.SysInfo
	2,  // 1: probe.v1.Report.cpu:type_name -> probe.v1.CPU
	3,  // 2: probe.v1.Report.load:type_name -> probe.v1.Load
	4,  // 3: probe.v1.Report.mem:type_name -> probe.v1.Mem
	5,  // 4: probe.v1.Report.sockets:type_name -> probe.v1.Sockets
	6,  // 5: probe.v1.Report.disks:type_name -> probe.v1.Disk
	7,  // 6: probe.v1.Report.net:type_name -> probe.v1.NetRate
	8,  // 7: probe.v1.Report.traffic:type_name -> probe.v1.IfaceTraffic
	10, // 8: probe.v1.Report.pings:type_name -> probe.v1.Ping
	9,  // 9: probe.v1.IfaceTraffic.cur:type_name -> probe.v1.Period
	9,  // 10: probe.v1.IfaceTraffic.prev:type_name -> probe.v1.Period
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_probe_v1_probe_proto_init() }
func file_proto_probe_v1_probe_proto_init() {
	if File_proto_probe_v1_probe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_probe_v1_probe_proto_rawDesc), len(file_proto_probe_v1_probe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_probe_v1_probe_proto_goTypes,
		DependencyIndexes: file_proto_probe_v1_probe_proto_depIdxs,
		MessageInfos:      file_proto_probe_v1_probe_proto_msgTypes,
	}.Build()
	File_proto_probe_v1_probe_proto = out.File
	file_proto_probe_v1_probe_proto_goTypes = nil
	file_proto_probe_v1_probe_proto_depIdxs = nil
}
