#!/bin/sh
# Writes THIRD_PARTY_LICENSES: the license files of everything linked into or
# embedded in the release binaries (Go modules for all release arches, the Go
# standard library, the vendored web libraries). Run via `make licenses`;
# `make dist` regenerates it so a release never ships a stale copy.
set -eu
cd "$(dirname "$0")/.."

ARCHES=${ARCHES:-amd64 arm64}
out=THIRD_PARTY_LICENSES
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

# "path version dir" of every non-main module the commands depend on.
mods=$(for arch in $ARCHES; do
	CGO_ENABLED=0 GOOS=linux GOARCH=$arch go list -deps \
		-f '{{with .Module}}{{if not .Main}}{{.Path}} {{.Version}} {{.Dir}}{{end}}{{end}}' ./cmd/...
done | sort -u)

# License, notice and patent files at the root of a directory.
legal() {
	find "$1" -maxdepth 1 -type f | grep -E '/(LICEN[CS]E|COPYING|NOTICE|PATENTS)[^/]*$' | sort
}

section() { # title, files...
	title=$1; shift
	printf '\n%s\n%s\n' "================================================================" "$title"
	for f in "$@"; do
		printf '\n---- %s ----\n\n' "$(basename "$f")"
		cat "$f"
	done
}

{
	echo "Third-party software in the vps-probe release binaries"
	echo
	echo "Generated by scripts/third_party_licenses.sh; do not edit by hand."
	echo "The binaries statically link the Go standard library and the Go modules"
	echo "below; vps-probe-server also embeds Apache ECharts in its web UI."
	echo
	echo "- Go standard library"
	echo "$mods" | while read -r path ver dir; do echo "- $path $ver"; done
	echo "- Apache ECharts $(ls web/static/vendor | sed -n 's/^echarts-\([0-9.]*\)\.min\.js$/\1/p')"

	# Debian-style Go packages drop $GOROOT/LICENSE; the standard library
	# license is the same text as golang.org/x/sys's, which is always linked.
	golic=$(go env GOROOT)/LICENSE
	if [ ! -f "$golic" ]; then
		golic=$(echo "$mods" | awk '$1 == "golang.org/x/sys" { print $3 "/LICENSE" }')
	fi
	section "Go standard library" "$golic"

	echo "$mods" | while read -r path ver dir; do
		if [ -z "$(legal "$dir")" ]; then
			echo "licenses: no license file in $path $ver" >&2
			exit 1
		fi
		# shellcheck disable=SC2046 # file names from module roots have no spaces
		section "$path $ver" $(legal "$dir")
	done

	section "Apache ECharts" web/static/vendor/echarts-NOTICE web/static/vendor/echarts-LICENSE
} >"$tmp"

chmod 0644 "$tmp"
mv "$tmp" "$out"
trap - EXIT
echo "licenses: $out"
