package config

import (
	"fmt"
	"net"
	"strings"
)

// AgentConfig renders agent.yml for one node: its token, and every other
// node that has an addr as a ping peer. The result is a local file for the
// agent; nothing is ever pushed to agents.
func (c *Config) AgentConfig(id, serverAddr string) (string, error) {
	n, ok := c.Node(id)
	if !ok {
		return "", fmt.Errorf("node %q is not in the config", id)
	}
	if _, port, err := net.SplitHostPort(serverAddr); err != nil || port == "" {
		return "", fmt.Errorf("server address %q: want host:port as the agent should reach it, e.g. 203.0.113.1:9527", serverAddr)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by `vps-probe-server agent-config %s`. Install with:\n", id)
	fmt.Fprintf(&b, "#   ./install.sh agent --config <this file>\n")
	fmt.Fprintf(&b, "# Contains this node's token: keep it private (mode 0600).\n\n")
	fmt.Fprintf(&b, "node: %q\n", n.ID)
	fmt.Fprintf(&b, "server:\n  addr: %q\n  token: %q\n", serverAddr, n.Token)
	fmt.Fprintf(&b, "interval: 10s\nstate_dir: /var/lib/vps-probe\ndisks: [\"/\"]\n")
	fmt.Fprintf(&b, "interfaces: []            # empty = auto-detect physical NICs\n")
	fmt.Fprintf(&b, "traffic:\n  timezone: %q   # must match the server's timezone\n  reset_day: %d\n", c.Timezone, n.ResetDay)
	fmt.Fprintf(&b, "ping:\n  interval: 1s\n  timeout: 2s\n")
	var peers, missing []string
	for _, p := range c.Nodes {
		switch {
		case p.ID == id:
		case p.Addr == "":
			missing = append(missing, p.ID)
		default:
			peers = append(peers, fmt.Sprintf("    - { name: %q, addr: %q }\n", p.ID, p.Addr))
		}
	}
	if len(peers) == 0 {
		b.WriteString("  peers: []\n")
	} else {
		b.WriteString("  peers:\n" + strings.Join(peers, ""))
	}
	if len(missing) > 0 {
		fmt.Fprintf(&b, "  # Not pinged (no addr in server.yml): %s\n", strings.Join(missing, ", "))
	}
	return b.String(), nil
}
